version: "3.6"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    environment:
      TZ: Asia/Shanghai
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    depends_on:
      - web-admin
    restart: always
    networks:
      - default

  web-admin:
    build:
      context: './bid-go/web-admin'
      args:
        RUN_MODE: ${RUN_MODE}
    container_name: web-admin
    environment:
      TZ: Asia/Shanghai
    stdin_open: true
    volumes:
      - /home/log/:/home/log/:rw
      - /dnmp/www/web_admin/upload/:/var/www/html/web_admin/upload/:rw
      - /dnmp/bid-go/web-admin/static_ace/:/var/www/html/web_admin/static_ace/:rw
    depends_on:
      - mysql
      - redis
    ports:
      - "8003:8003"
    restart: always
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: Asia/Shanghai

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${REDIS_LOG_DIR}:/var/log/redis/:rw
      - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf:ro
      - ${REDIS_DIR}:/var/lib/redis/6379/:rw
    command:
      - /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - default
    ports:
      - "${REDIS_HOST_PORT}:6379"

networks:
  default:
