version: "3.6"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    depends_on:
      - web-api
      - php72
    restart: always
    networks:
      - default

  php72:
    build:
      context: . 
      args:
        PHP_VERSION: ${PHP72_VERSION}        
        PHP_SWOOLE: ${PHP72_SWOOLE}
        PHP_REDIS: ${PHP72_REDIS}
        PHP_YAF: ${PHP72_YAF}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    container_name: php72
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP72_LOG_FILE}:/var/log/php/:rw
      - /home/log/:/home/log/:rw
    restart: always
    depends_on:
      - mysql
      - redis
    cap_add:
      - SYS_PTRACE
    networks:
      - default
  
  web-api:
    build: 
      context: './bid-go/web-api'
    container_name: web-api
    stdin_open: true
    volumes:
      - /home/log/:/home/log/:rw
    depends_on:
      - mysql
      - redis
    ports:
      - "8003:8003"
    restart: always    
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:${REDIS_VERSION}   
    container_name: redis 
    volumes:
      - ${REDIS_LOG_DIR}:/var/log/redis/:rw
      - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf:ro
      - ${REDIS_DIR}:/var/lib/redis/6379/:rw
    command:
      - /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - default
    ports:
      - "${REDIS_HOST_PORT}:6379"  

networks:
  default:
