version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - default

   web-api:
    build: 
      context: './bid-go/web-api'
    container_name: web-api
    stdin_open: true
    volumes:
      - /home/log/:/home/log/:rw
    ports:
      - "8003:8003"
    restart: always    
    networks:
      - default
  
  web-admin:
    build: './bid-go/web-admin'
    container_name: web-admin
    stdin_open: true
    command: ./web_admin -e pro
    volumes:
      - /opt/go/web/src/web_admin:/go/src/web_admin
      - /home/log/:/home/log/:rw
    ports:
      - "8001:8001"
    restart: always

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
      - /home/log/:/home/log/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  redis:
    image: redis:${REDIS_VERSION}    
    volumes:
      - ${REDIS_LOG_DIR}:/var/log/redis/:rw
      - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf:ro
      - ${REDIS_DIR}:/var/lib/redis/6379/:rw
    command:
      - /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - default
    ports:
      - "${REDIS_HOST_PORT}:6379"  

networks:
  default:
